[package]
name = "pantheon-migrate"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
pantheon-core = { path = "../pantheon-core" }
pantheon-extensions = { path = "../pantheon-extensions" }
pantheon-storage = { path = "../pantheon-storage" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

[lints]
workspace = true
