//! Bundled skills: shipped inside the binary, materialized into
//! `<data_dir>/skills/` on first use so the standard discovery sees them.
//!
//! A bundled skill is ordinary `SKILL.md` data once on disk. It is not a
//! capability: `skill_read` stays gated on FilesystemRead and the model
//! reads it like any other skill. Bundling solves only one problem: a fresh
//! install has an empty skills dir, so the shipped knowledge would never
//! reach the session.
//!
//! Layout: `crates/pantheon-exec/bundled-skills/<name>/SKILL.md`, plus
//! optional `scripts/` and `references/` trees. The registry is GENERATED
//! by `build.rs` from those directories (`BundledSkill`, `BundledSkillFile`,
//! `bundled_skills()` below come from OUT_DIR) - adding a skill is adding
//! a directory, no code changes. Seeding materializes the full tree:
//! write-if-missing, with the content-stamp behavior for SKILL.md and a
//! hash manifest for the bundled files, so a user editing the materialized
//! copy is never overwritten.

use crate::skills::{parse_skill, SkillExecRuntime};
use pantheon_api::error::{Layer, PantheonError};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

// Generated by build.rs from bundled-skills/*/: BundledSkill,
// BundledSkillFile, bundled_skills().
include!(concat!(env!("OUT_DIR"), "/bundled_skills_registry.rs"));

fn serr(code: &str, cause: String) -> PantheonError {
    PantheonError::new(
        code,
        Layer::Execution,
        false,
        cause,
        "check bundled skill content",
        "",
    )
}

/// Validate a bundled skill through the same parser discovery uses, so a
/// malformed entry fails loudly instead of seeding a skill that then
/// silently fails to load. Also proves every non-npx executable points
/// at a bundled script: a typo in `command:` would otherwise seed a
/// skill whose executables fail at every invocation.
fn validate(bundled: &BundledSkill) -> Result<(), PantheonError> {
    let path = Path::new("bundled-skills/<name>/SKILL.md");
    let skill = parse_skill(bundled.content, path)?;
    if skill.meta.name.trim().is_empty() {
        return Err(serr(
            "SKILL_NO_NAME",
            "bundled skill frontmatter has no name".into(),
        ));
    }
    for exec in &skill.meta.exec {
        if exec.runtime == SkillExecRuntime::Npx {
            continue;
        }
        if !bundled.files.iter().any(|f| f.path == exec.command) {
            return Err(serr(
                "SKILL_BAD_EXEC",
                format!(
                    "bundled skill '{}', executable '{}': script {:?} is not bundled \
                     (add it under scripts/)",
                    skill.meta.name, exec.name, exec.command
                ),
            ));
        }
    }
    Ok(())
}

/// Materialize every bundled skill into `<data_dir>/skills/<name>/`.
///
/// Per skill:
/// - SKILL.md: target missing → write it (first run); target exists with
///   the stamp comment matching this build → rewrite it (binary updated,
///   user never edited); target exists with a different stamp → leave it
///   alone (user edit wins).
/// - `scripts/` + `references/` files: write-if-missing; an existing file
///   is refreshed only when its on-disk hash still matches the hash
///   recorded in `.pantheon-bundled.json` (i.e. the user never touched
///   it). A user-edited file is never overwritten. (The manifest replaces
///   the inline stamp for scripts because appending an HTML comment to a
///   shell script would break it.)
fn seed_bundled_skill(
    skills_dir: &Path,
    bundled: &BundledSkill,
) -> Result<SeedOutcome, PantheonError> {
    validate(bundled)?;
    let dir = skills_dir.join(bundled.dir_name);
    let target = dir.join("SKILL.md");
    let stamp = stamp_for(bundled.content);

    let md_outcome = if !target.exists() {
        fs::create_dir_all(&dir).map_err(|e| {
            serr(
                "SKILL_SEED_IO",
                format!("cannot create {}: {e}", dir.display()),
            )
        })?;
        fs::write(&target, stamped(bundled.content, &stamp)).map_err(|e| {
            serr(
                "SKILL_SEED_IO",
                format!("cannot write {}: {e}", target.display()),
            )
        })?;
        SeedOutcome::Created
    } else {
        let existing = fs::read_to_string(&target).map_err(|e| {
            serr(
                "SKILL_SEED_IO",
                format!("cannot read {}: {e}", target.display()),
            )
        })?;
        if existing.contains(&stamp) {
            fs::write(&target, stamped(bundled.content, &stamp)).map_err(|e| {
                serr(
                    "SKILL_SEED_IO",
                    format!("cannot refresh {}: {e}", target.display()),
                )
            })?;
            SeedOutcome::Refreshed
        } else {
            SeedOutcome::KeptUserCopy
        }
    };

    let files_outcome = seed_bundled_files(&dir, bundled)?;
    Ok(match (md_outcome, files_outcome) {
        (SeedOutcome::Created, _) | (_, SeedOutcome::Created) => SeedOutcome::Created,
        (SeedOutcome::Refreshed, _) | (_, SeedOutcome::Refreshed) => SeedOutcome::Refreshed,
        _ => SeedOutcome::KeptUserCopy,
    })
}

/// Manifest recording which bundled files this build seeded and their
/// content hashes. Lives at `<skill_dir>/.pantheon-bundled.json`; the
/// refresh rule mirrors the SKILL.md stamp: a file whose on-disk hash
/// still matches the manifest entry was never user-edited, so a binary
/// update may rewrite it.
const BUNDLED_MANIFEST: &str = ".pantheon-bundled.json";

/// Seed the bundled `scripts/` + `references/` files. Returns per-file
/// aggregate outcome (no files → KeptUserCopy, neutral).
fn seed_bundled_files(dir: &Path, bundled: &BundledSkill) -> Result<SeedOutcome, PantheonError> {
    if bundled.files.is_empty() {
        return Ok(SeedOutcome::KeptUserCopy);
    }
    let manifest_path = dir.join(BUNDLED_MANIFEST);
    let mut manifest: HashMap<String, String> = fs::read_to_string(&manifest_path)
        .ok()
        .and_then(|t| serde_json::from_str::<HashMap<String, String>>(&t).ok())
        .unwrap_or_default();
    let mut outcome = SeedOutcome::KeptUserCopy;
    let mut changed = false;
    for f in bundled.files {
        // Defense in depth: the registry is generated from our own tree,
        // but a `..` here must never escape the skill dir.
        if f.path.split('/').any(|s| s.is_empty() || s == "..") {
            return Err(serr(
                "SKILL_SEED_PATH",
                format!("bundled file path escapes: {:?}", f.path),
            ));
        }
        let target: PathBuf = f
            .path
            .split('/')
            .fold(dir.to_path_buf(), |p, seg| p.join(seg));
        let hash = simple_hash(f.content);
        if !target.exists() {
            if let Some(parent) = target.parent() {
                fs::create_dir_all(parent).map_err(|e| {
                    serr(
                        "SKILL_SEED_IO",
                        format!("cannot create {}: {e}", parent.display()),
                    )
                })?;
            }
            fs::write(&target, f.content).map_err(|e| {
                serr(
                    "SKILL_SEED_IO",
                    format!("cannot write {}: {e}", target.display()),
                )
            })?;
            manifest.insert(f.path.to_string(), hash);
            changed = true;
            outcome = SeedOutcome::Created;
            continue;
        }
        // Refresh only when the on-disk content is byte-identical to what
        // we last seeded (manifest hash matches disk hash): untouched.
        let disk_hash = fs::read(&target)
            .ok()
            .map(|b| simple_hash(&String::from_utf8_lossy(&b)))
            .unwrap_or_default();
        let pristine = manifest
            .get(f.path)
            .map(|recorded| *recorded == disk_hash)
            .unwrap_or(false);
        if pristine && disk_hash != hash {
            fs::write(&target, f.content).map_err(|e| {
                serr(
                    "SKILL_SEED_IO",
                    format!("cannot refresh {}: {e}", target.display()),
                )
            })?;
            manifest.insert(f.path.to_string(), hash);
            changed = true;
            if outcome == SeedOutcome::KeptUserCopy {
                outcome = SeedOutcome::Refreshed;
            }
        }
        // Else: user-edited (or seeded before the manifest existed)
        // never overwrite.
    }
    if changed {
        let tmp = dir.join(format!("{BUNDLED_MANIFEST}.tmp"));
        fs::write(
            &tmp,
            serde_json::to_string_pretty(&manifest).unwrap_or_default(),
        )
        .map_err(|e| {
            serr(
                "SKILL_SEED_IO",
                format!("cannot write {}: {e}", tmp.display()),
            )
        })?;
        fs::rename(&tmp, &manifest_path).map_err(|e| {
            serr(
                "SKILL_SEED_IO",
                format!("cannot write {}: {e}", manifest_path.display()),
            )
        })?;
    }
    Ok(outcome)
}

/// Marker comment that records which bundled content version a materialized
/// copy holds. Sits at the very end, below everything the parser and the
/// model care about.
fn stamp_for(content: &str) -> String {
    format!("<!-- pantheon:bundled:{} -->", simple_hash(content))
}

fn stamped(content: &str, stamp: &str) -> String {
    format!("{content}\n{stamp}\n")
}

/// FNV-1a over the SKILL.md content, hex-encoded. Content-addressed, not
/// hand-versioned: any edit to the source file changes the stamp.
fn simple_hash(content: &str) -> String {
    let mut hash: u64 = 0xcbf29ce484222325;
    for byte in content.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{hash:016x}")
}

/// What happened to one bundled skill during seeding.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeedOutcome {
    /// Wrote a fresh copy.
    Created,
    /// Rewrote an untouched copy to match this build.
    Refreshed,
    /// Left the on-disk copy alone; a user edit is present.
    KeptUserCopy,
}

/// Seed all bundled skills into `data_dir/skills` and return one outcome
/// per skill, in `bundled_skills()` order. Called from session construction
/// before discovery runs.
pub fn seed_bundled_skills(data_dir: &Path) -> Vec<(String, SeedOutcome)> {
    let skills_dir = data_dir.join("skills");
    bundled_skills()
        .into_iter()
        .map(|s| {
            let outcome = seed_bundled_skill(&skills_dir, &s);
            match outcome {
                Ok(o) => (s.dir_name.to_string(), o),
                // A failed seed must not take the session down: log-and-
                // continue, discovery still sees whatever is on disk.
                Err(e) => {
                    eprintln!("bundled skill '{}' failed to seed: {e}", s.dir_name);
                    (s.dir_name.to_string(), SeedOutcome::KeptUserCopy)
                }
            }
        })
        .collect()
}
