/* Bundled-skill registry generator.

Shared between `build.rs` (via `include!`) and unit tests (via
`#[path = "../build-support/gen.rs"]` in the crate's test build).
Walks `bundled-skills/<name>/`, collecting `SKILL.md` plus every text
file under `scripts/` and `references/`, and renders the Rust registry
source with `include_str!` embeddings.

Content workers add skills by adding directories - no code changes,
no per-skill hand edits. Only UTF-8 text files are embedded; anything
else is reported as skipped so a stray binary never breaks the build.

NOTE: this file is `include!`d mid-file by build.rs, so it must not
start with inner (`//!`) doc comments. */

use std::path::{Path, PathBuf};

/// One bundled skill found on disk.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BundledSkillDef {
    /// Directory name under `bundled-skills/` (also the seed target name).
    pub dir_name: String,
    /// Absolute path to SKILL.md.
    pub skill_md: PathBuf,
    /// (relative path with `/` separators, absolute path) for each
    /// embedded text file under `scripts/` or `references/`.
    pub files: Vec<(String, PathBuf)>,
}

/// Non-UTF8 files met during the walk: skipped with a build warning.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkippedBinary {
    pub skill: String,
    pub rel: String,
}

/// Skill-dir slug rule, mirroring `pantheon_exec::skills::valid_slug`
/// (ASCII alphanumerics plus `-`/`_`, 1..=64). The build script cannot
/// depend on the crate it builds, so the rule is duplicated here and
/// covered by the tests below.
fn valid_slug(s: &str) -> bool {
    let b = s.as_bytes();
    !b.is_empty()
        && b.len() <= 64
        && b.iter()
            .all(|c| c.is_ascii_alphanumeric() || *c == b'-' || *c == b'_')
}

/// Discover bundled skills under `root` (`crates/pantheon-exec/bundled-skills`).
/// Returns `(skills, skipped_binaries)`, skills sorted by dir name for a
/// deterministic registry. Directories without a SKILL.md are ignored.
pub fn discover_bundled_skills(root: &Path) -> (Vec<BundledSkillDef>, Vec<SkippedBinary>) {
    let mut skills = Vec::new();
    let mut skipped = Vec::new();
    let Ok(entries) = std::fs::read_dir(root) else {
        return (skills, skipped);
    };
    let mut dirs: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();
    for dir in dirs {
        let Some(name) = dir.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name.starts_with('.') {
            continue;
        }
        if !valid_slug(name) {
            eprintln!("bundled-skills: skipping directory with invalid slug: {name:?}");
            continue;
        }
        let skill_md = dir.join("SKILL.md");
        if !skill_md.is_file() {
            continue;
        }
        let mut files = Vec::new();
        for sub in ["scripts", "references"] {
            collect_text_files(&dir.join(sub), sub, name, &mut files, &mut skipped);
        }
        files.sort();
        skills.push(BundledSkillDef {
            dir_name: name.to_string(),
            skill_md,
            files,
        });
    }
    (skills, skipped)
}

/// Recursively collect UTF-8 text files under `dir`; `rel_prefix` is the
/// already-accumulated relative path (`scripts`, `references`, ...).
fn collect_text_files(
    dir: &Path,
    rel_prefix: &str,
    skill: &str,
    files: &mut Vec<(String, PathBuf)>,
    skipped: &mut Vec<SkippedBinary>,
) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    let mut paths: Vec<PathBuf> = entries.flatten().map(|e| e.path()).collect();
    paths.sort();
    for p in paths {
        let Some(name) = p.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if name.starts_with('.') {
            continue;
        }
        if p.is_dir() {
            collect_text_files(&p, &format!("{rel_prefix}/{name}"), skill, files, skipped);
        } else if p.is_file() {
            let rel = format!("{rel_prefix}/{name}");
            match std::fs::read(&p) {
                Ok(bytes) if std::str::from_utf8(&bytes).is_ok() => files.push((rel, p)),
                _ => skipped.push(SkippedBinary {
                    skill: skill.to_string(),
                    rel,
                }),
            }
        }
    }
}

/// Render the registry Rust source. Each file is embedded with
/// `include_str!` at an ABSOLUTE path, so content is read at crate
/// compile time (fresh on every build) rather than serialized into the
/// generated source as escaped literals.
pub fn render_registry_rs(defs: &[BundledSkillDef]) -> String {
    let mut out = String::from("// @generated by crates/pantheon-exec/build.rs - do not edit.\n");
    out.push_str(
        "pub struct BundledSkillFile {\n    pub path: &'static str,\n    pub content: &'static str,\n}\n",
    );
    out.push_str(
        "pub struct BundledSkill {\n    pub dir_name: &'static str,\n    pub content: &'static str,\n    pub files: &'static [BundledSkillFile],\n}\n",
    );
    out.push_str("pub fn bundled_skills() -> Vec<BundledSkill> {\n    vec![\n");
    for d in defs {
        out.push_str(&format!(
            "        BundledSkill {{\n            dir_name: {:?},\n            content: include_str!({:?}),\n            files: &[\n",
            d.dir_name,
            d.skill_md.to_string_lossy(),
        ));
        for (rel, abs) in &d.files {
            out.push_str(&format!(
                "                BundledSkillFile {{ path: {rel:?}, content: include_str!({:?}) }},\n",
                abs.to_string_lossy(),
            ));
        }
        out.push_str("            ],\n        },\n");
    }
    out.push_str("    ]\n}\n");
    out
}

